"""Generate SYNTHETIC HMO benefit documents, for testing a benefits-schedule reader.

Why these exist
---------------
`hmo_published_tiers.csv` carries four numbers per plan: the MBL and the room entitlement.
A real Summary of Benefits carries perhaps forty, and several of them bind BEFORE the MBL
does -- per-procedure sub-limits, an outpatient diagnostics ceiling, a first-year cap on
pre-existing conditions, professional fees drawn from the same pot. Our waterfall models
none of that, so on a laparoscopic cholecystectomy it can credit an HMO with ten times
what a real schedule would pay.

Reading those documents is the fix, and a reader needs documents to be tested against.
Real ones cannot go in a public repo: they are somebody's actual policy, they name a
member, and the ones circulating online are re-uploads of employer contracts.

What is real here and what is not
---------------------------------
REAL, and sourced:
  - the tier names, MBLs and room entitlements  (maxicare.com.ph, see HMO_TIERS_PROVENANCE)
  - the SHAPE of a schedule of benefits: the section order, the "subject to MBL" phrasing,
    a Special Modalities table of per-procedure caps, pre-existing coverage scaled by group
    headcount, 80% reimbursement for emergencies at non-accredited hospitals. All of that
    is how the Bureau of Customs' published HMO procurement documents are laid out.

INVENTED, and must never be quoted as anyone's terms:
  - every peso figure that is not an MBL: the sub-limits, the outpatient ceiling, the
    first-year pre-existing caps, the co-insurance percentages
  - the members, employers, certificate numbers, dates and hotlines

Every page says so, in a banner and a watermark, because an unmarked specimen is exactly
the thing that gets mistaken for ground truth six weeks later.

Run:  python data/build_benefits_specimens.py
"""

import json
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

OUT_DIR = Path(__file__).resolve().parent / "benefits_specimens"

BANNER = ("SYNTHETIC SPECIMEN &mdash; GENERATED TEST DATA &mdash; NOT A POLICY DOCUMENT. "
          "Members, employers, certificate numbers and all peso limits other than the "
          "Maximum Benefit Limit are invented.")

INK = colors.HexColor("#0f172a")
MUTE = colors.HexColor("#64748b")
LINE = colors.HexColor("#cbd5e1")
ACCENT = colors.HexColor("#0e7490")


# ----------------------------------------------------------------- page furniture
def _watermark(canvas, doc):
    """Diagonal SPECIMEN across every page, plus a footer naming the generator.

    Drawn under nothing -- it goes on top of the content deliberately. A watermark a
    screenshot can crop out is not a watermark.
    """
    canvas.saveState()
    canvas.setFont("Helvetica-Bold", 62)
    canvas.setFillColor(colors.Color(0.85, 0.87, 0.91, alpha=0.55))
    canvas.translate(A4[0] / 2, A4[1] / 2)
    canvas.rotate(38)
    canvas.drawCentredString(0, 0, "SYNTHETIC SPECIMEN")
    canvas.restoreState()

    canvas.saveState()
    canvas.setFont("Helvetica", 6.5)
    canvas.setFillColor(MUTE)
    canvas.drawString(18 * mm, 11 * mm,
                      "Synthetic test data generated by data/build_benefits_specimens.py. "
                      "Not issued by any health maintenance organisation.")
    canvas.drawRightString(A4[0] - 18 * mm, 11 * mm, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def _styles() -> dict:
    ss = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("t", parent=ss["Title"], fontSize=15, leading=19,
                                textColor=INK, spaceAfter=2),
        "sub": ParagraphStyle("s", parent=ss["Normal"], fontSize=8.5, leading=11,
                              textColor=MUTE, alignment=TA_CENTER, spaceAfter=8),
        "banner": ParagraphStyle("b", parent=ss["Normal"], fontSize=7.5, leading=9.5,
                                 textColor=colors.HexColor("#9a3412"), alignment=TA_CENTER),
        "h": ParagraphStyle("h", parent=ss["Heading2"], fontSize=10.5, leading=13,
                            textColor=ACCENT, spaceBefore=10, spaceAfter=4),
        "body": ParagraphStyle("p", parent=ss["Normal"], fontSize=8.5, leading=11.5,
                               textColor=INK, spaceAfter=4),
        "cell": ParagraphStyle("c", parent=ss["Normal"], fontSize=8, leading=10,
                               textColor=INK),
        "small": ParagraphStyle("sm", parent=ss["Normal"], fontSize=7.5, leading=9.5,
                                textColor=MUTE),
    }


def _banner_block(st: dict) -> list:
    box = Table([[Paragraph(BANNER, st["banner"])]], colWidths=[172 * mm])
    box.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#f97316")),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fff7ed")),
        ("LEFTPADDING", (0, 0), (-1, -1), 6), ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return [box, Spacer(1, 7)]


def _table(rows: list, st: dict, widths: list, header: bool = True) -> Table:
    data = [[Paragraph(str(c), st["cell"]) for c in r] for r in rows]
    t = Table(data, colWidths=widths, repeatRows=1 if header else 0)
    style = [
        ("GRID", (0, 0), (-1, -1), 0.4, LINE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]
    if header:
        style += [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#ecfeff")),
                  ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")]
    t.setStyle(TableStyle(style))
    return t


def _build(path: Path, story: list) -> None:
    doc = SimpleDocTemplate(
        str(path), pagesize=A4,
        leftMargin=19 * mm, rightMargin=19 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
        title=f"SYNTHETIC SPECIMEN - {path.stem}", author="build_benefits_specimens.py",
        subject="Synthetic test fixture. Not a policy document.",
    )
    doc.build(story, onFirstPage=_watermark, onLaterPages=_watermark)


# ----------------------------------------------------------------- specimen 1
def individual_certificate(st: dict) -> tuple:
    """MyMaxicare individual tier, as a Certificate of Coverage.

    Prose-heavy with one small table -- the shape an individual member actually receives,
    and the easier of the two to parse. Real MBL and room entitlement; everything else
    invented.
    """
    s = _banner_block(st)
    s += [
        Paragraph("CERTIFICATE OF COVERAGE", st["title"]),
        Paragraph("Individual and Family Healthcare Program &bull; Specimen copy",
                  st["sub"]),
    ]

    s.append(_table([
        ["Member", "DELA CRUZ, JUAN ANTONIO M. (specimen)"],
        ["Certificate No.", "SPEC-IND-2026-000144"],
        ["Plan", "MyMaxicare Gold"],
        ["Provider", "Maxicare Healthcare Corporation"],
        ["Effective", "01 March 2026 to 28 February 2027"],
        ["Maximum Benefit Limit", "PhP150,000.00 per illness per year"],
        ["Room and Board", "Regular Private"],
    ], st, [42 * mm, 130 * mm], header=False))

    s += [
        Paragraph("I. In-Patient Benefits", st["h"]),
        Paragraph(
            "Room and board accommodation per the member's entitled category. Use of "
            "operating room, intensive care unit, isolation and recovery room; medicines "
            "and intravenous fluids; blood products including screening and cross "
            "matching; diagnostic, therapeutic and laboratory procedures incidental to "
            "confinement; anaesthesia and its administration; oxygen and its "
            "administration &mdash; all subject to the Maximum Benefit Limit.", st["body"]),
        Paragraph(
            "<b>Professional fees</b> of the attending physician, surgeon and "
            "anaesthesiologist are covered and are <b>charged against the same Maximum "
            "Benefit Limit</b>.", st["body"]),
        Paragraph(
            "Benefits are payable only after PhilHealth benefits have been applied. Where "
            "the member is not PhilHealth-eligible, the deductible equivalent of the "
            "applicable case rate shall be for the member's account.", st["body"]),

        Paragraph("II. Out-Patient Benefits", st["h"]),
        Paragraph(
            "Consultations during regular clinic hours with an affiliated physician, "
            "unlimited as to number. Laboratory examinations, x-rays and routine "
            "diagnostic procedures upon the written prescription of an affiliated "
            "physician, up to <b>PhP20,000.00 per member per year</b>. Minor surgery not "
            "requiring confinement, up to <b>PhP15,000.00 per procedure</b>. Treatment of "
            "minor injuries such as lacerations, mild burns and sprains, including "
            "dressings, sutures and conventional casts.", st["body"]),
        Paragraph(
            "Out-patient laboratory and diagnostic procedures require a Letter of "
            "Authorization issued prior to availment. Procedures availed without a Letter "
            "of Authorization are reimbursable at 80% of the actual cost.", st["body"]),

        Paragraph("III. Special Modalities and Procedures", st["h"]),
        Paragraph(
            "The following are covered whether performed on an in-patient or out-patient "
            "basis, up to the sub-limit stated, and in no case beyond the Maximum Benefit "
            "Limit:", st["body"]),
    ]

    s.append(_table([
        ["Procedure", "Limit per member per year"],
        ["Laparoscopic cholecystectomy", "PhP60,000.00"],
        ["Laparoscopic appendectomy", "PhP50,000.00"],
        ["Magnetic Resonance Imaging (MRI)", "PhP18,000.00"],
        ["CT scan, with or without contrast", "PhP15,000.00"],
        ["Extracorporeal shock wave lithotripsy", "PhP45,000.00"],
        ["Hysteroscopic myoma resection", "PhP45,000.00"],
        ["Cataract extraction, per eye", "PhP40,000.00"],
        ["Haemodialysis, per session", "PhP4,000.00"],
        ["All other non-conventional but medically necessary procedures",
         "PhP10,000.00"],
    ], st, [118 * mm, 54 * mm]))

    s += [
        Paragraph("IV. Emergency Care", st["h"]),
        Paragraph(
            "In an accredited hospital, emergency room services are covered subject to the "
            "Maximum Benefit Limit. In a <b>non-accredited</b> hospital within the "
            "Philippines, hospital charges and professional fees are reimbursed at "
            "<b>80%</b>, up to PhP30,000.00 per availment, for the first 24 hours of "
            "treatment. Reimbursement is at 100% where the nearest accredited facility is "
            "more than 50 kilometres away.", st["body"]),

        Paragraph("V. Pre-Existing Conditions", st["h"]),
        Paragraph(
            "A condition is pre-existing where, at any time before the effective date, the "
            "member sought or received medical advice, diagnosis, care or treatment for "
            "it; or the condition was evident or manifest to the member; or its natural "
            "progression indicates that its onset occurred before the effective date, "
            "whether or not the member was aware of it.", st["body"]),
    ]

    s.append(_table([
        ["Membership year", "Non-dreaded condition", "Dreaded condition"],
        ["First year", "Up to PhP20,000.00", "Up to PhP20,000.00"],
        ["Second year onwards", "Up to the Maximum Benefit Limit",
         "Up to the Maximum Benefit Limit, if acquired after the effective date"],
    ], st, [36 * mm, 60 * mm, 76 * mm]))

    s += [
        Paragraph("VI. General Exclusions", st["h"]),
        Paragraph(
            "Cosmetic surgery and procedures for beautification. Dental services except as "
            "provided under an optional dental rider. Corrective eyeglasses, contact "
            "lenses and hearing aids. Infertility management and reversal of "
            "sterilisation. Psychiatric and psychological conditions except as expressly "
            "covered. Injuries arising from participation in a criminal act, from "
            "self-inflicted injury, or while under the influence of alcohol or a "
            "prohibited drug. Custodial, domiciliary and rest cures. Experimental or "
            "investigational treatment. Injuries arising from war, insurrection, or "
            "participation in a riot. Sports-related injuries from professional athletics, "
            "motor racing, mountaineering and scuba diving.", st["body"]),
        Spacer(1, 6),
        Paragraph(
            "This specimen was generated for software testing. It confers no benefit, "
            "represents no contract, and states no organisation's actual terms.",
            st["small"]),
    ]

    truth = {
        "document": "individual_certificate_gold.pdf",
        "doc_type": "certificate_of_coverage",
        "provider": "Maxicare",
        "plan_name": "Gold",
        "mbl_annual": 150000,
        "mbl_basis": "per_illness_per_year",
        "room_entitlement": "Regular Private",
        "coverage_pct": 1.0,
        "professional_fees_within_mbl": True,
        "philhealth_applied_first": True,
        "outpatient_diagnostics_limit": 20000,
        "outpatient_requires_loa": True,
        "outpatient_no_loa_reimbursement_pct": 0.8,
        "procedure_sublimits": {
            "LAPAROSCOPIC CHOLECYSTECTOMY": 60000,
            "LAPAROSCOPIC APPENDECTOMY": 50000,
            "MRI": 18000,
            "CT SCAN": 15000,
            "EXTRACORPOREAL SHOCK WAVE LITHOTRIPSY": 45000,
            "HYSTEROSCOPIC MYOMA RESECTION": 45000,
            "CATARACT EXTRACTION": 40000,
            "HAEMODIALYSIS": 4000,
        },
        "default_procedure_sublimit": 10000,
        "emergency_non_accredited_pct": 0.8,
        "emergency_non_accredited_cap": 30000,
        "preexisting_first_year_limit": 20000,
        "preexisting_subsequent": "up_to_mbl",
        "exclusion_count": 11,
    }
    return s, truth


# ----------------------------------------------------------------- specimen 2
def corporate_summary(st: dict) -> tuple:
    """Employer group Summary of Benefits: dense, tabular, two member categories.

    The hard case, and the realistic one. Coverage differs by employee category, the
    limits live in a grid rather than in prose, and pre-existing cover is scaled by
    headcount the way the published government contracts do it.
    """
    s = _banner_block(st)
    s += [
        Paragraph("SUMMARY OF BENEFITS", st["title"]),
        Paragraph("Group Healthcare Program &bull; Specimen copy", st["sub"]),
    ]

    s.append(_table([
        ["Account", "NORTHGATE LOGISTICS CORPORATION (specimen employer)"],
        ["Policy No.", "SPEC-GRP-2026-00877"],
        ["Provider", "Maxicare Healthcare Corporation"],
        ["Contract year", "01 April 2026 to 31 March 2027"],
        ["Principal members enrolled", "246"],
        ["Eligible dependents", "No limit as to number; enrolled at the member's cost"],
    ], st, [46 * mm, 126 * mm], header=False))

    s += [Paragraph("A. Benefit Limits by Category", st["h"])]
    s.append(_table([
        ["Category", "Maximum Benefit Limit", "Room and Board", "Co-insurance"],
        ["Officers and Managers", "PhP200,000.00 per illness per year",
         "Regular Private", "None"],
        ["Supervisory", "PhP150,000.00 per illness per year", "Regular Private", "None"],
        ["Rank and File", "PhP100,000.00 per illness per year", "Semi - Private",
         "20% of charges in excess of PhP80,000.00"],
    ], st, [34 * mm, 58 * mm, 42 * mm, 38 * mm]))

    s += [Paragraph(
        "Room and board is covered up to the rate of the member's entitled category. "
        "Where a member occupies accommodation above the entitled category, the "
        "difference in room rate and the corresponding increase in professional fees and "
        "ancillary charges shall be for the member's own account.", st["body"])]

    s += [Paragraph("B. In-Patient Benefits", st["h"])]
    s.append(_table([
        ["Benefit", "Limit"],
        ["Room and board", "Per entitled category, above"],
        ["Operating room, ICU, isolation, recovery room", "Subject to MBL"],
        ["Professional fees &mdash; physician, surgeon, anaesthesiologist",
         "Subject to MBL"],
        ["Medicines, IV fluids, blood products and cross matching", "Subject to MBL"],
        ["Diagnostics and laboratory incidental to confinement", "Subject to MBL"],
        ["Dressings, conventional casts and sutures", "Subject to MBL"],
    ], st, [118 * mm, 54 * mm]))

    s += [Paragraph("C. Out-Patient Benefits", st["h"])]
    s.append(_table([
        ["Benefit", "Limit"],
        ["Consultations during regular clinic hours", "Unlimited, excluding medicines"],
        ["X-ray, laboratory and routine diagnostics on prescription",
         "PhP25,000.00 per member per year"],
        ["Minor surgery not requiring confinement", "PhP20,000.00 per procedure"],
        ["Pre-natal and post-natal consultations",
         "Up to ten (10), excluding laboratory"],
        ["Physical therapy, on referral", "PhP12,000.00 per member per year"],
        ["Speech therapy, stroke patients only", "PhP8,000.00 per member per year"],
    ], st, [104 * mm, 68 * mm]))

    s.append(PageBreak())
    s += _banner_block(st)

    s += [Paragraph("D. Special Modalities and Procedures", st["h"]),
          Paragraph(
              "Covered at actual cost up to the sub-limit stated, whether performed on an "
              "in-patient or out-patient basis. The sub-limit binds first; the Maximum "
              "Benefit Limit binds thereafter. Amounts in excess are for the member's "
              "account.", st["body"])]
    s.append(_table([
        ["Procedure", "Officers / Supervisory", "Rank and File"],
        ["Laparoscopic cholecystectomy", "PhP50,000.00", "PhP35,000.00"],
        ["Laparoscopic appendectomy", "PhP45,000.00", "PhP30,000.00"],
        ["Percutaneous ultrasonic nephrolithotomy", "PhP45,000.00", "PhP30,000.00"],
        ["Extracorporeal shock wave lithotripsy", "PhP40,000.00", "PhP25,000.00"],
        ["Hysteroscopic myoma resection", "PhP40,000.00", "PhP25,000.00"],
        ["Magnetic Resonance Imaging (MRI)", "PhP15,000.00", "PhP10,000.00"],
        ["CT scan, with or without contrast", "PhP12,000.00", "PhP9,000.00"],
        ["2D echocardiography with Doppler", "PhP8,000.00", "PhP6,000.00"],
        ["Cataract extraction, per eye", "PhP35,000.00", "PhP25,000.00"],
        ["Haemodialysis, per session", "PhP4,000.00", "PhP3,500.00"],
        ["Sleep study / polysomnogram", "PhP15,000.00", "PhP10,000.00"],
        ["Cryosurgery", "PhP15,000.00", "PhP10,000.00"],
        ["All other non-conventional but medically necessary procedures",
         "PhP10,000.00", "PhP5,000.00"],
    ], st, [96 * mm, 40 * mm, 36 * mm]))

    s += [Paragraph("E. Pre-Existing Conditions", st["h"]),
          Paragraph(
              "Coverage for pre-existing conditions is determined by the number of "
              "principal members enrolled at the start of the contract year:", st["body"])]
    s.append(_table([
        ["Principal members enrolled", "Pre-existing coverage"],
        ["100 or more", "Up to 100% of the Maximum Benefit Limit"],
        ["75 to 99", "Up to 70% of the Maximum Benefit Limit"],
        ["50 to 74", "Up to 50% of the Maximum Benefit Limit"],
        ["26 to 49", "Up to 10% of the Maximum Benefit Limit"],
        ["10 to 25", "Subject to a one (1) year contestability period"],
    ], st, [86 * mm, 86 * mm]))
    s += [Paragraph(
        "This account is enrolled at 246 principal members. Pre-existing conditions are "
        "therefore covered up to 100% of the applicable Maximum Benefit Limit. Dreaded "
        "conditions existing prior to the effective date are covered up to "
        "PhP50,000.00 during the first contract year.", st["body"])]

    s += [Paragraph("F. Emergency Care", st["h"])]
    s.append(_table([
        ["Situation", "Coverage"],
        ["Accredited hospital", "Subject to MBL"],
        ["Non-accredited hospital, within the Philippines",
         "80% reimbursement of hospital bills and professional fees, up to "
         "PhP40,000.00 per availment"],
        ["More than 50 km from any accredited facility", "100% reimbursement, subject to MBL"],
        ["Emergency care abroad", "80% reimbursement per case per member per year, "
                                  "subject to MBL"],
        ["Ambulance conduction to an affiliated institution",
         "PhP2,500.00 per conduction, reimbursable"],
    ], st, [70 * mm, 102 * mm]))

    s += [Paragraph("G. Availment", st["h"]),
          Paragraph(
              "A Letter of Authorization is required for all elective admissions and for "
              "out-patient laboratory and diagnostic procedures, and shall be issued "
              "within twenty (20) minutes of request during business hours. Benefits are "
              "applied after PhilHealth. Members are responsible for ensuring that their "
              "PhilHealth contributions are current; where PhilHealth benefits are denied "
              "for lapsed contributions, the equivalent case rate shall be deducted from "
              "the claim and shall be for the member's account.", st["body"]),
          Paragraph(
              "Benefits are payable only at facilities accredited under this contract at "
              "the time of availment. The accredited network is subject to change without "
              "prior notice; members should verify a facility's status before admission.",
              st["body"])]

    s += [Paragraph("H. General Exclusions", st["h"]),
          Paragraph(
              "Cosmetic surgery and beautification. Dental services except under the "
              "optional rider. Eyeglasses, contact lenses, hearing aids and prosthetic "
              "appliances. Infertility management and reversal of sterilisation. "
              "Psychiatric and psychological conditions except as expressly covered. "
              "Injuries from a criminal act, self-inflicted injury, or intoxication. "
              "Custodial and rest cures. Experimental treatment. War, insurrection and "
              "riot. Professional athletics and hazardous sports. Occupational injuries "
              "compensable under the Employees' Compensation Commission.", st["body"]),
          Spacer(1, 6),
          Paragraph(
              "This specimen was generated for software testing. It confers no benefit, "
              "represents no contract, and states no organisation's actual terms.",
              st["small"])]

    truth = {
        "document": "corporate_summary_of_benefits.pdf",
        "doc_type": "summary_of_benefits",
        "provider": "Maxicare",
        "plan_name": None,
        "employer": "Northgate Logistics Corporation (specimen)",
        "principal_members": 246,
        "mbl_basis": "per_illness_per_year",
        "categories": {
            "Officers and Managers": {"mbl_annual": 200000,
                                      "room_entitlement": "Regular Private",
                                      "coverage_pct": 1.0},
            "Supervisory": {"mbl_annual": 150000,
                            "room_entitlement": "Regular Private",
                            "coverage_pct": 1.0},
            "Rank and File": {"mbl_annual": 100000,
                              "room_entitlement": "Semi - Private",
                              "coverage_pct": 0.8,
                              "coinsurance_applies_above": 80000},
        },
        "professional_fees_within_mbl": True,
        "philhealth_applied_first": True,
        "room_excess_for_member_account": True,
        "outpatient_diagnostics_limit": 25000,
        "outpatient_requires_loa": True,
        "procedure_sublimits": {
            "LAPAROSCOPIC CHOLECYSTECTOMY": {"officers": 50000, "rank_and_file": 35000},
            "LAPAROSCOPIC APPENDECTOMY": {"officers": 45000, "rank_and_file": 30000},
            "PERCUTANEOUS ULTRASONIC NEPHROLITHOTOMY": {"officers": 45000,
                                                        "rank_and_file": 30000},
            "EXTRACORPOREAL SHOCK WAVE LITHOTRIPSY": {"officers": 40000,
                                                      "rank_and_file": 25000},
            "HYSTEROSCOPIC MYOMA RESECTION": {"officers": 40000, "rank_and_file": 25000},
            "MRI": {"officers": 15000, "rank_and_file": 10000},
            "CT SCAN": {"officers": 12000, "rank_and_file": 9000},
            "2D ECHOCARDIOGRAPHY": {"officers": 8000, "rank_and_file": 6000},
            "CATARACT EXTRACTION": {"officers": 35000, "rank_and_file": 25000},
            "HAEMODIALYSIS": {"officers": 4000, "rank_and_file": 3500},
            "SLEEP STUDY": {"officers": 15000, "rank_and_file": 10000},
            "CRYOSURGERY": {"officers": 15000, "rank_and_file": 10000},
        },
        "default_procedure_sublimit": {"officers": 10000, "rank_and_file": 5000},
        "preexisting_pct_of_mbl": 1.0,
        "preexisting_rule": "scaled_by_group_size",
        "preexisting_dreaded_first_year_limit": 50000,
        "emergency_non_accredited_pct": 0.8,
        "emergency_non_accredited_cap": 40000,
        "accreditation_subject_to_change": True,
        "exclusion_count": 11,
    }
    return s, truth


# ----------------------------------------------------------------- specimen 3
def hr_one_pager(st: dict) -> tuple:
    """The sparse case: what HR actually emails you.

    Most of the fields a reader wants are simply absent. A reader that hallucinates a
    sub-limit here is worse than one that returns null, so this specimen exists to catch
    exactly that.
    """
    s = _banner_block(st)
    s += [
        Paragraph("HEALTH CARD BENEFITS &mdash; AT A GLANCE", st["title"]),
        Paragraph("Internal advisory to employees &bull; Specimen copy", st["sub"]),
        Paragraph(
            "Beginning 01 April 2026 our health card provider is Maxicare. Your card will "
            "be distributed through your department head. Please keep the details below "
            "for reference.", st["body"]),
    ]

    s.append(_table([
        ["What you get", "Details"],
        ["Plan", "Silver"],
        ["Maximum Benefit Limit", "PhP100,000.00 per illness, per year"],
        ["Room and board", "Semi - Private"],
        ["Dependents", "May be enrolled at your own cost through HR"],
        ["Effectivity", "01 April 2026"],
        ["Hotline", "(02) 8000-0000 (specimen number, not in service)"],
    ], st, [52 * mm, 120 * mm]))

    s += [
        Paragraph(
            "<b>Before any admission or laboratory test</b>, call the hotline for a Letter "
            "of Authorization. Walk-ins without one may be asked to pay first and claim "
            "reimbursement afterwards.", st["body"]),
        Paragraph(
            "PhilHealth is applied first, then your card. Please make sure your PhilHealth "
            "contributions are up to date &mdash; if PhilHealth denies your claim, the "
            "amount they would have paid is charged to you, not to the card.", st["body"]),
        Paragraph(
            "For the complete schedule of benefits, exclusions and pre-existing condition "
            "rules, request the benefit booklet from the HR Service Desk.", st["body"]),
        Spacer(1, 8),
        Paragraph(
            "This specimen was generated for software testing. It confers no benefit, "
            "represents no contract, and states no organisation's actual terms.",
            st["small"]),
    ]

    truth = {
        "document": "hr_one_pager.pdf",
        "doc_type": "hr_advisory",
        "provider": "Maxicare",
        "plan_name": "Silver",
        "mbl_annual": 100000,
        "mbl_basis": "per_illness_per_year",
        "room_entitlement": "Semi - Private",
        "philhealth_applied_first": True,
        "outpatient_requires_loa": True,
        # Everything below is ABSENT from the document. A reader must return null rather
        # than fill these in from what a plan of this tier usually carries.
        "coverage_pct": None,
        "professional_fees_within_mbl": None,
        "outpatient_diagnostics_limit": None,
        "procedure_sublimits": None,
        "preexisting_first_year_limit": None,
        "emergency_non_accredited_pct": None,
        "exclusion_count": None,
    }
    return s, truth


SPECIMENS = [
    ("individual_certificate_gold.pdf", individual_certificate),
    ("corporate_summary_of_benefits.pdf", corporate_summary),
    ("hr_one_pager.pdf", hr_one_pager),
]


def render_pages_as_png(pdf_path: Path) -> list:
    """Also emit page images, so the vision reader can be tested on these directly.

    The slip reader takes images, not PDFs. Without this the specimens would only be
    usable by a text extractor, which is the easy half of the problem.
    """
    import fitz

    out = []
    doc = fitz.open(pdf_path)
    for i, page in enumerate(doc):
        img = pdf_path.with_name(f"{pdf_path.stem}_p{i + 1}.png")
        page.get_pixmap(dpi=150).save(img)
        out.append(img)
    doc.close()
    return out


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    st = _styles()
    truths = []

    for name, builder in SPECIMENS:
        story, truth = builder(st)
        path = OUT_DIR / name
        _build(path, story)
        images = render_pages_as_png(path)
        truth["pages"] = len(images)
        truths.append(truth)
        print(f"  {path.name}  ({len(images)} page image(s))")

    gt = OUT_DIR / "groundtruth.json"
    gt.write_text(json.dumps(truths, indent=2), encoding="utf-8")
    print(f"  {gt.name}  ({len(truths)} specimens)")


if __name__ == "__main__":
    main()
